/*
 * Decompiled with CFR 0.152.
 */
package com.spire.presentation.packages;

import com.spire.presentation.packages.sprjv;
import com.spire.presentation.packages.sprlem;
import com.spire.presentation.packages.sprsra;
import com.spire.presentation.packages.sprzuo;

public interface sprbn {
    public static final sprlem cfr_renamed_41;
    public static final sprlem cfr_renamed_1337;
    public static final sprlem cfr_renamed_136;
    public static final sprlem cfr_renamed_615;
    public static final sprlem cfr_renamed_129;
    public static final sprlem cfr_renamed_1222;
    public static final sprlem cfr_renamed_1329;
    public static final sprlem cfr_renamed_1217;
    public static final sprlem cfr_renamed_1221;
    public static final sprlem cfr_renamed_725;
    public static final sprlem cfr_renamed_134;
    public static final sprlem cfr_renamed_954;
    public static final sprlem cfr_renamed_805;
    public static final sprlem cfr_renamed_131;
    public static final sprlem cfr_renamed_722;
    public static final sprlem cfr_renamed_955;
    public static final sprlem cfr_renamed_1228;
    public static final sprlem cfr_renamed_1260;
    public static final sprlem cfr_renamed_499;
    public static final sprlem cfr_renamed_135;
    public static final sprlem cfr_renamed_956;
    public static final sprlem cfr_renamed_952;
    public static final sprlem cfr_renamed_728;
    public static final sprlem cfr_renamed_128;
    public static final sprlem cfr_renamed_957;
    public static final sprlem cfr_renamed_314;
    public static final sprlem cfr_renamed_951;
    public static final sprlem cfr_renamed_84;
    public static final sprlem cfr_renamed_723;
    public static final sprlem cfr_renamed_1226;
    public static final sprlem cfr_renamed_287;
    public static final sprlem cfr_renamed_724;
    public static final sprlem cfr_renamed_953;
    public static final sprlem cfr_renamed_133;
    public static final sprlem cfr_renamed_185;
    public static final sprlem spr\ufe34;
    public static final sprlem cfr_renamed_82;
    public static final sprlem cfr_renamed_126;
    public static final sprlem cfr_renamed_88;
    public static final sprlem cfr_renamed_31;
    public static final sprlem cfr_renamed_272;
    public static final sprlem cfr_renamed_145;
    public static final sprlem cfr_renamed_114;
    public static final sprlem cfr_renamed_96;
    public static final sprlem cfr_renamed_105;
    public static final sprlem cfr_renamed_137;
    public static final sprlem cfr_renamed_79;
    public static final sprlem cfr_renamed_107;
    public static final sprlem cfr_renamed_132;
    public static final sprlem cfr_renamed_102;
    public static final sprlem cfr_renamed_93;
    public static final sprlem cfr_renamed_86;
    public static final sprlem cfr_renamed_152;
    public static final sprlem cfr_renamed_112;
    public static final sprlem cfr_renamed_119;
    public static final sprlem cfr_renamed_91;
    public static final sprlem cfr_renamed_0;
    public static final sprlem cfr_renamed_1;
    public static final sprlem cfr_renamed_2;
    public static final sprlem cfr_renamed_3;
    public static final sprlem cfr_renamed_4;

    static {
        cfr_renamed_132 = new sprlem(sprsra.cfr_renamed_9("PEREWEPEUEPEYXQZOXOZOXO^OXOY"));
        cfr_renamed_955 = cfr_renamed_132.cfr_renamed_1436("1");
        cfr_renamed_145 = cfr_renamed_132.cfr_renamed_1436(sprzuo.cfr_renamed_9("\\"));
        cfr_renamed_41 = cfr_renamed_132.cfr_renamed_1436(sprsra.cfr_renamed_9("X"));
        cfr_renamed_952 = cfr_renamed_132.cfr_renamed_1436(sprzuo.cfr_renamed_9("Z"));
        cfr_renamed_953 = cfr_renamed_132.cfr_renamed_1436(sprsra.cfr_renamed_9("^"));
        cfr_renamed_954 = new sprlem("1.3.6.1.4.1.8301.3.1.3.3");
        cfr_renamed_314 = cfr_renamed_954.cfr_renamed_1436("1");
        cfr_renamed_1228 = cfr_renamed_954.cfr_renamed_1436(sprzuo.cfr_renamed_9("\\"));
        cfr_renamed_2 = cfr_renamed_954.cfr_renamed_1436(sprsra.cfr_renamed_9("X"));
        cfr_renamed_951 = cfr_renamed_954.cfr_renamed_1436(sprzuo.cfr_renamed_9("Z"));
        cfr_renamed_119 = cfr_renamed_954.cfr_renamed_1436(sprsra.cfr_renamed_9("^"));
        cfr_renamed_112 = new sprlem("1.3.6.1.4.1.8301.3.1.3.4.1");
        cfr_renamed_102 = new sprlem("1.3.6.1.4.1.8301.3.1.3.4.2");
        cfr_renamed_4 = new sprlem("1.3.6.1.4.1.8301.3.1.3.4.2.1");
        cfr_renamed_805 = new sprlem("1.3.6.1.4.1.8301.3.1.3.4.2.2");
        cfr_renamed_134 = new sprlem("1.3.6.1.4.1.8301.3.1.3.4.2.3");
        cfr_renamed_82 = sprjv.cfr_renamed_1447;
        cfr_renamed_1226 = sprjv.cfr_renamed_813;
        cfr_renamed_722 = sprjv.cfr_renamed_1510;
        cfr_renamed_1221 = sprjv.cfr_renamed_1513;
        cfr_renamed_128 = sprjv.cfr_renamed_112;
        cfr_renamed_1329 = sprjv.cfr_renamed_2414;
        cfr_renamed_91 = sprjv.cfr_renamed_93;
        cfr_renamed_86 = sprjv.cfr_renamed_314;
        cfr_renamed_93 = sprjv.cfr_renamed_624;
        cfr_renamed_129 = sprjv.cfr_renamed_1205;
        cfr_renamed_31 = sprjv.cfr_renamed_1261;
        cfr_renamed_105 = sprjv.cfr_renamed_284;
        cfr_renamed_287 = sprjv.cfr_renamed_134;
        cfr_renamed_1260 = sprjv.cfr_renamed_3059;
        cfr_renamed_84 = sprjv.cfr_renamed_614;
        cfr_renamed_956 = sprjv.cfr_renamed_2824;
        cfr_renamed_88 = sprjv.cfr_renamed_2797;
        cfr_renamed_126 = sprjv.cfr_renamed_1763;
        cfr_renamed_185 = sprjv.cfr_renamed_1521;
        cfr_renamed_107 = sprjv.cfr_renamed_1512;
        cfr_renamed_1337 = sprjv.cfr_renamed_1260;
        spr\ufe34 = sprjv.cfr_renamed_1532;
        cfr_renamed_131 = sprjv.cfr_renamed_1344;
        cfr_renamed_96 = cfr_renamed_91;
        cfr_renamed_728 = cfr_renamed_86;
        cfr_renamed_135 = cfr_renamed_93;
        cfr_renamed_136 = cfr_renamed_129;
        cfr_renamed_272 = cfr_renamed_956;
        cfr_renamed_3 = cfr_renamed_88;
        cfr_renamed_725 = cfr_renamed_126;
        cfr_renamed_724 = cfr_renamed_185;
        cfr_renamed_133 = sprjv.cfr_renamed_953;
        cfr_renamed_1222 = sprjv.cfr_renamed_725;
        cfr_renamed_615 = sprjv.cfr_renamed_2409;
        cfr_renamed_1 = new sprlem(sprzuo.cfr_renamed_9("b@aX~Vd^~_~_aZ`\\g@h^~[~_~_"));
        cfr_renamed_0 = new sprlem(sprsra.cfr_renamed_9("SEP]OSU[OZOZP_QYVEY[O^OZOY"));
        cfr_renamed_1217 = new sprlem(sprzuo.cfr_renamed_9("b@aX~Vd^~_~_aZ`\\g@h^~[~_~]"));
        cfr_renamed_114 = new sprlem(sprsra.cfr_renamed_9("SEP]OSU[OZOZP_QYVEY[O^OZO_"));
        cfr_renamed_499 = new sprlem(sprzuo.cfr_renamed_9("b@aX~Vd^~_~_aZ`\\g@h^~[~_~["));
        cfr_renamed_152 = new sprlem(sprsra.cfr_renamed_9("SEP]OSU[OZOZP_QYVEY[O^OZO]"));
        cfr_renamed_957 = new sprlem(sprzuo.cfr_renamed_9("b@aX~Vd^~_~_aZ`\\g@h^~[~_~Y"));
        cfr_renamed_723 = new sprlem(sprsra.cfr_renamed_9("SEP]OSU[OZOZP_QYVEY[O^OZOS"));
        cfr_renamed_79 = new sprlem(sprzuo.cfr_renamed_9("b@aX~Vd^~_~_aZ`\\g@h^~[~_~W"));
        cfr_renamed_137 = new sprlem(sprsra.cfr_renamed_9("YOZWEY_QEPEPZU[S\\OSQETEPEP["));
    }
}

