/*
 * Decompiled with CFR 0.152.
 */
package com.spire.presentation.packages;

import com.spire.presentation.packages.sprbr;
import com.spire.presentation.packages.sprdl;
import com.spire.presentation.packages.sprdt;
import com.spire.presentation.packages.sprgp;
import com.spire.presentation.packages.sprgt;
import com.spire.presentation.packages.sprhr;
import com.spire.presentation.packages.sprhv;
import com.spire.presentation.packages.spris;
import com.spire.presentation.packages.sprlem;
import com.spire.presentation.packages.sprow;
import com.spire.presentation.packages.sprqo;
import com.spire.presentation.packages.sprsx;
import com.spire.presentation.packages.sprwr;

public class sprpsl {
    public static final sprlem cfr_renamed_1197;
    public static final sprlem cfr_renamed_1397;
    public static final sprlem cfr_renamed_1223;
    public static final sprlem cfr_renamed_1344;
    public static final sprlem cfr_renamed_1472;
    public static final sprlem cfr_renamed_1442;
    public static final sprlem cfr_renamed_1328;
    public static final sprlem cfr_renamed_41;
    public static final sprlem cfr_renamed_1337;
    public static final sprlem cfr_renamed_136;
    public static final sprlem cfr_renamed_615;
    public static final sprlem cfr_renamed_129;
    public static final sprlem cfr_renamed_1222;
    public static final sprlem cfr_renamed_1329;
    public static final sprlem cfr_renamed_1217;
    public static final sprlem cfr_renamed_1221;
    public static final sprlem cfr_renamed_725;
    public static final sprlem cfr_renamed_134;
    public static final sprlem cfr_renamed_954;
    public static final sprlem cfr_renamed_805;
    public static final sprlem cfr_renamed_131;
    public static final sprlem cfr_renamed_722;
    public static final sprlem cfr_renamed_955;
    public static final sprlem cfr_renamed_1228;
    public static final sprlem cfr_renamed_1260;
    public static final sprlem cfr_renamed_499;
    public static final sprlem cfr_renamed_135;
    public static final sprlem cfr_renamed_956;
    public static final sprlem cfr_renamed_952;
    public static final sprlem cfr_renamed_728;
    public static final sprlem cfr_renamed_128;
    public static final sprlem cfr_renamed_957;
    public static final sprlem cfr_renamed_314;
    public static final sprlem cfr_renamed_951;
    public static final sprlem cfr_renamed_84;
    public static final sprlem cfr_renamed_723;
    public static final sprlem cfr_renamed_1226;
    public static final sprlem cfr_renamed_287;
    public static final sprlem cfr_renamed_724;
    public static final sprlem cfr_renamed_953;
    public static final sprlem cfr_renamed_133;
    public static final sprlem cfr_renamed_185;
    public static final sprlem spr\ufe34;
    public static final sprlem cfr_renamed_82;
    public static final sprlem cfr_renamed_126;
    public static final sprlem cfr_renamed_88;
    public static final sprlem cfr_renamed_31;
    public static final sprlem cfr_renamed_272;
    public static final sprlem cfr_renamed_145;
    public static final sprlem cfr_renamed_114;
    public static final sprlem cfr_renamed_96;
    public static final sprlem cfr_renamed_105;
    public static final sprlem cfr_renamed_137;
    public static final sprlem cfr_renamed_79;
    public static final sprlem cfr_renamed_107;
    public static final sprlem cfr_renamed_132;
    public static final sprlem cfr_renamed_102;
    public static final sprlem cfr_renamed_93;
    public static final sprlem cfr_renamed_86;
    public static final sprlem cfr_renamed_152;
    public static final sprlem cfr_renamed_112;
    public static final sprlem cfr_renamed_119;
    public static final sprlem cfr_renamed_91;
    public static final sprlem cfr_renamed_0;
    public static final sprlem cfr_renamed_1;
    public static final sprlem cfr_renamed_2;
    public static final sprlem cfr_renamed_3;
    public static final sprlem cfr_renamed_4;

    static {
        cfr_renamed_1442 = sprgt.cfr_renamed_2.cfr_renamed_9910();
        cfr_renamed_1222 = sprdl.cfr_renamed_2797.cfr_renamed_9910();
        cfr_renamed_3 = sprdl.cfr_renamed_1479.cfr_renamed_9910();
        cfr_renamed_1260 = sprow.cfr_renamed_953.cfr_renamed_9910();
        cfr_renamed_1329 = sprow.cfr_renamed_107.cfr_renamed_9910();
        cfr_renamed_272 = sprwr.cfr_renamed_88.cfr_renamed_9910();
        cfr_renamed_723 = sprwr.cfr_renamed_1223.cfr_renamed_9910();
        cfr_renamed_102 = sprwr.cfr_renamed_724.cfr_renamed_9910();
        cfr_renamed_1 = sprwr.cfr_renamed_951.cfr_renamed_9910();
        cfr_renamed_152 = sprwr.cfr_renamed_107.cfr_renamed_9910();
        cfr_renamed_1228 = sprwr.cfr_renamed_1228.cfr_renamed_9910();
        cfr_renamed_1226 = sprwr.cfr_renamed_134.cfr_renamed_9910();
        cfr_renamed_107 = sprwr.cfr_renamed_133.cfr_renamed_9910();
        cfr_renamed_114 = sprwr.cfr_renamed_805.cfr_renamed_9910();
        cfr_renamed_1221 = sprsx.cfr_renamed_2.cfr_renamed_9910();
        cfr_renamed_1217 = sprsx.cfr_renamed_1.cfr_renamed_9910();
        cfr_renamed_499 = sprsx.cfr_renamed_4.cfr_renamed_9910();
        cfr_renamed_724 = sprqo.cfr_renamed_132.cfr_renamed_9910();
        cfr_renamed_953 = sprgp.cfr_renamed_4.cfr_renamed_9910();
        cfr_renamed_957 = sprdl.cfr_renamed_152.cfr_renamed_9910();
        cfr_renamed_1337 = sprwr.cfr_renamed_136.cfr_renamed_9910();
        cfr_renamed_88 = sprwr.cfr_renamed_287.cfr_renamed_9910();
        cfr_renamed_615 = sprwr.cfr_renamed_3.cfr_renamed_9910();
        cfr_renamed_91 = sprsx.cfr_renamed_91.cfr_renamed_9910();
        cfr_renamed_128 = sprsx.cfr_renamed_0.cfr_renamed_9910();
        cfr_renamed_185 = sprsx.cfr_renamed_3.cfr_renamed_9910();
        cfr_renamed_133 = sprgp.cfr_renamed_3.cfr_renamed_9910();
        cfr_renamed_84 = sprqo.cfr_renamed_119.cfr_renamed_9910();
        cfr_renamed_1223 = sprqo.cfr_renamed_3.cfr_renamed_9910();
        cfr_renamed_112 = sprbr.cfr_renamed_725.cfr_renamed_9910();
        cfr_renamed_96 = sprbr.cfr_renamed_137.cfr_renamed_9910();
        cfr_renamed_136 = sprbr.cfr_renamed_96.cfr_renamed_9910();
        cfr_renamed_129 = sprhr.cfr_renamed_952.cfr_renamed_9910();
        cfr_renamed_126 = sprhr.cfr_renamed_31.cfr_renamed_9910();
        cfr_renamed_0 = sprhr.cfr_renamed_96.cfr_renamed_9910();
        cfr_renamed_93 = sprhr.cfr_renamed_86.cfr_renamed_9910();
        cfr_renamed_82 = sprhr.cfr_renamed_1226.cfr_renamed_9910();
        cfr_renamed_1344 = sprhr.cfr_renamed_955.cfr_renamed_9910();
        cfr_renamed_41 = sprhr.cfr_renamed_499.cfr_renamed_9910();
        cfr_renamed_86 = sprhr.cfr_renamed_119.cfr_renamed_9910();
        cfr_renamed_105 = sprhr.cfr_renamed_723.cfr_renamed_9910();
        cfr_renamed_145 = sprhr.cfr_renamed_1228.cfr_renamed_9910();
        cfr_renamed_137 = sprhr.cfr_renamed_126.cfr_renamed_9910();
        cfr_renamed_952 = sprhr.cfr_renamed_135.cfr_renamed_9910();
        cfr_renamed_1397 = sprqo.cfr_renamed_93.cfr_renamed_9910();
        cfr_renamed_805 = sprdt.cfr_renamed_79.cfr_renamed_9910();
        cfr_renamed_4 = sprdt.cfr_renamed_93.cfr_renamed_9910();
        cfr_renamed_135 = sprhv.cfr_renamed_132;
        cfr_renamed_132 = sprhv.cfr_renamed_272;
        cfr_renamed_722 = sprhv.cfr_renamed_79;
        cfr_renamed_314 = sprhv.spr\ufe34;
        cfr_renamed_954 = sprdl.cfr_renamed_1205;
        cfr_renamed_728 = sprdl.cfr_renamed_1456;
        cfr_renamed_725 = sprdl.cfr_renamed_722;
        cfr_renamed_1472 = sprgt.cfr_renamed_0.cfr_renamed_9910();
        cfr_renamed_2 = sprwr.cfr_renamed_957.cfr_renamed_9910();
        cfr_renamed_1197 = sprwr.cfr_renamed_1226.cfr_renamed_9910();
        cfr_renamed_955 = sprwr.cfr_renamed_112.cfr_renamed_9910();
        cfr_renamed_119 = sprwr.cfr_renamed_272.cfr_renamed_9910();
        cfr_renamed_956 = sprdl.cfr_renamed_1540.cfr_renamed_9910();
        cfr_renamed_79 = sprqo.cfr_renamed_112.cfr_renamed_9910();
        cfr_renamed_134 = sprdt.cfr_renamed_4.cfr_renamed_9910();
        spr\ufe34 = sprdt.cfr_renamed_3.cfr_renamed_9910();
        cfr_renamed_287 = spris.cfr_renamed_91.cfr_renamed_9910();
        cfr_renamed_131 = spris.cfr_renamed_272.cfr_renamed_9910();
        cfr_renamed_951 = spris.cfr_renamed_102.cfr_renamed_9910();
        cfr_renamed_31 = sprwr.cfr_renamed_314.cfr_renamed_9910();
        cfr_renamed_1328 = sprwr.cfr_renamed_2.cfr_renamed_9910();
    }
}

