/*
 * Decompiled with CFR 0.152.
 */
package com.spire.presentation.packages;

import com.spire.presentation.packages.sprdfq;
import com.spire.presentation.packages.sprlem;
import com.spire.presentation.packages.sprmiaa;

public interface sprrq {
    public static final sprlem cfr_renamed_1344;
    public static final sprlem cfr_renamed_1472;
    public static final sprlem cfr_renamed_1442;
    public static final sprlem cfr_renamed_1328;
    public static final sprlem cfr_renamed_41;
    public static final sprlem cfr_renamed_1337;
    public static final sprlem cfr_renamed_136;
    public static final sprlem cfr_renamed_615;
    public static final sprlem cfr_renamed_129;
    public static final sprlem cfr_renamed_1222;
    public static final sprlem cfr_renamed_1329;
    public static final sprlem cfr_renamed_1217;
    public static final sprlem cfr_renamed_1221;
    public static final sprlem cfr_renamed_725;
    public static final sprlem cfr_renamed_134;
    public static final sprlem cfr_renamed_954;
    public static final sprlem cfr_renamed_805;
    public static final sprlem cfr_renamed_131;
    public static final sprlem cfr_renamed_722;
    public static final sprlem cfr_renamed_955;
    public static final sprlem cfr_renamed_1228;
    public static final sprlem cfr_renamed_1260;
    public static final sprlem cfr_renamed_499;
    public static final sprlem cfr_renamed_135;
    public static final sprlem cfr_renamed_956;
    public static final sprlem cfr_renamed_952;
    public static final sprlem cfr_renamed_728;
    public static final sprlem cfr_renamed_128;
    public static final sprlem cfr_renamed_957;
    public static final sprlem cfr_renamed_314;
    public static final sprlem cfr_renamed_951;
    public static final sprlem cfr_renamed_84;
    public static final sprlem cfr_renamed_723;
    public static final sprlem cfr_renamed_1226;
    public static final sprlem cfr_renamed_287;
    public static final sprlem cfr_renamed_724;
    public static final sprlem cfr_renamed_953;
    public static final sprlem cfr_renamed_133;
    public static final sprlem cfr_renamed_185;
    public static final sprlem spr\ufe34;
    public static final sprlem cfr_renamed_82;
    public static final sprlem cfr_renamed_126;
    public static final sprlem cfr_renamed_88;
    public static final sprlem cfr_renamed_31;
    public static final sprlem cfr_renamed_272;
    public static final sprlem cfr_renamed_145;
    public static final sprlem cfr_renamed_114;
    public static final sprlem cfr_renamed_96;
    public static final sprlem cfr_renamed_105;
    public static final sprlem cfr_renamed_137;
    public static final sprlem cfr_renamed_79;
    public static final sprlem cfr_renamed_107;
    public static final sprlem cfr_renamed_132;
    public static final sprlem cfr_renamed_102;
    public static final sprlem cfr_renamed_93;
    public static final sprlem cfr_renamed_86;
    public static final sprlem cfr_renamed_152;
    public static final sprlem cfr_renamed_112;
    public static final sprlem cfr_renamed_119;
    public static final sprlem cfr_renamed_91;
    public static final sprlem cfr_renamed_0;
    public static final sprlem cfr_renamed_1;
    public static final sprlem cfr_renamed_2;
    public static final sprlem cfr_renamed_3;
    public static final sprlem cfr_renamed_4;

    static {
        cfr_renamed_2 = new sprlem(sprmiaa.cfr_renamed_9("'8$8'# 8'&'/!8'"));
        cfr_renamed_136 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^ @ "));
        cfr_renamed_1228 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&'8$"));
        cfr_renamed_287 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^ @\""));
        spr\ufe34 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&'8\""));
        cfr_renamed_728 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^#@ "));
        cfr_renamed_126 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&$8$"));
        cfr_renamed_272 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^#@\""));
        cfr_renamed_128 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&$8\""));
        cfr_renamed_1226 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^#@$"));
        cfr_renamed_1 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&$8 "));
        cfr_renamed_185 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^\"@ "));
        cfr_renamed_86 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&%8$"));
        cfr_renamed_954 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^\"@\""));
        cfr_renamed_952 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&%8\""));
        cfr_renamed_114 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^\"@$"));
        cfr_renamed_88 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&%8 "));
        cfr_renamed_135 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@ "));
        cfr_renamed_3 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8$"));
        cfr_renamed_1337 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@\""));
        cfr_renamed_1328 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8\""));
        cfr_renamed_134 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@$"));
        cfr_renamed_953 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8 "));
        cfr_renamed_93 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@&"));
        cfr_renamed_119 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8."));
        cfr_renamed_1260 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@("));
        cfr_renamed_133 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8'&"));
        cfr_renamed_1442 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("_!Z?_ "));
        cfr_renamed_152 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("'&\"8'$"));
        cfr_renamed_105 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9(" ^%@ ^!"));
        cfr_renamed_131 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$&'"));
        cfr_renamed_1217 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("\"^ "));
        cfr_renamed_82 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("%&'8'"));
        cfr_renamed_957 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("\"^ @#"));
        cfr_renamed_129 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("%&'8%"));
        cfr_renamed_96 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("\"^ @ ^ "));
        cfr_renamed_615 = cfr_renamed_129.cfr_renamed_1436("1");
        cfr_renamed_951 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$"));
        cfr_renamed_4 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("#@ "));
        cfr_renamed_1329 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$8$"));
        cfr_renamed_41 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("#@\""));
        cfr_renamed_145 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$8\""));
        cfr_renamed_31 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("#@$"));
        cfr_renamed_722 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$8 "));
        cfr_renamed_112 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("#@&"));
        cfr_renamed_91 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$8."));
        cfr_renamed_102 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("#@("));
        cfr_renamed_0 = cfr_renamed_129.cfr_renamed_1436(sprmiaa.cfr_renamed_9("$8'&"));
        cfr_renamed_84 = cfr_renamed_129.cfr_renamed_1436(sprdfq.cfr_renamed_9("\\?_ "));
        cfr_renamed_1222 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("%&$"));
        cfr_renamed_955 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("\"^#@ "));
        cfr_renamed_956 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("%&$8$"));
        cfr_renamed_79 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("\"^#@\""));
        cfr_renamed_1344 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("\"&'"));
        cfr_renamed_723 = cfr_renamed_1344.cfr_renamed_1436(sprdfq.cfr_renamed_9("#"));
        cfr_renamed_1472 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("#&'"));
        cfr_renamed_725 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("$^#"));
        cfr_renamed_107 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("#&%"));
        cfr_renamed_499 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("$^%"));
        cfr_renamed_132 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("#&#"));
        cfr_renamed_1221 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("$^'"));
        cfr_renamed_137 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("#&!"));
        cfr_renamed_724 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("$\\!"));
        cfr_renamed_805 = cfr_renamed_2.cfr_renamed_1436(sprmiaa.cfr_renamed_9("#$'"));
        cfr_renamed_314 = cfr_renamed_2.cfr_renamed_1436(sprdfq.cfr_renamed_9("$\\#"));
    }
}

